<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Flex.Auth</AssemblyName>
    <RootNamespace>Flex.Auth</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Flex.Infrastructures\Flex.Infrastructures.csproj" />
  </ItemGroup>

</Project>
